name: Welcome New Followers

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual trigger

jobs:
  check_new_followers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Get Current Followers
        id: get_followers
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.GitHubActionsToken }}" \
          https://api.github.com/orgs/Narcoguard/followers > followers.json
          
          # Extract usernames into a file
          jq -r '.[].login' followers.json > current_followers.txt
          
          # Initialize previous_followers.txt if not present
          if [ ! -f previous_followers.txt ]; then
            touch previous_followers.txt
          fi

      - name: Check for New Followers
        id: check_new
        run: |
          # Compare current followers to previous followers and find new ones
          new_followers=$(comm -23 <(sort current_followers.txt) <(sort previous_followers.txt))
          
          # Output the new followers
          echo "New followers: $new_followers"
          echo "::set-output name=new_followers::$new_followers"

      - name: Send Welcome Message
        if: steps.check_new.outputs.new_followers != ''
        run: |
          for follower in ${{ steps.check_new.outputs.new_followers }}; do
            echo "Sending welcome message to $follower"
            curl -X POST -H "Authorization: Bearer ${{ secrets.GitHubActionsToken }}" \
            -d "{\"title\":\"Welcome to NarcoGuard!\",\"body\":\"Hi @$follower, welcome to the NarcoGuard Organization! 🎉 \n\nWe are excited to have you here. For now, check out our [GitHub Organization](https://github.com/Narcoguard) to learn more about what we do.\n\nIf you are interested in joining as a member, please open an issue using [this link](https://github.com/Narcoguard/issues/new?template=membership-request.md).\"}" \
            https://api.github.com/repos/Narcoguard/Narcoguard/issues
          done

      - name: Update Previous Followers
        run: |
          cp current_followers.txt previous_followers.txt
