name: Project Idea Submission Auto-Reply

on:
  issues:
    types: [opened]

jobs:
  auto-reply:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the issue is created using project_idea_submission template
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GitHubActionsToken }}
          script: |
            const issue_number = context.payload.issue.number;
            const repo_owner = context.repo.owner;
            const repo_name = context.repo.repo;
            const issue_body = context.payload.issue.body;

            // Check if the issue was created using the 'project_idea_submission' template
            if (issue_body.includes('## Project Idea Submission')) {
              // Auto-reply message for project idea submission
              const auto_reply_message = `
              ✅ Thank you for your project idea submission.
              Your idea will be reviewed, and if it is good, we will work on the project!
              `;

              // Post the auto-reply message
              await github.rest.issues.createComment({
                owner: repo_owner,
                repo: repo_name,
                issue_number: issue_number,
                body: auto_reply_message
              });
            } else {
              console.log("Issue was not created using the 'project_idea_submission' template. No reply sent.");
            }
